### ISSUE TITLE
Mockthereum launch helper is not exported

### ISSUE THREAD

**Issue by jasperverbeet** [httptoolkit/mockthereum#1]
According to the README.md, the package exports `mockthereum`, which probably refers to https://github.com/httptoolkit/mockthereum/blob/main/src/admin-bin.ts. 

> To do this, you just need to run the admin server before you start your tests, and stop it afterwards. You can do that in one of two ways:
>
>You can run your test suite using the provided launch helper:
> ```
> mockthereum -c <your test command>
> ```

There doesn't seem to be any exported bin in the package under `/node_modules/.bin` or `/node_modules/mockthereum/bin`.

I've gotten everything to work by copying the `mockthereum`-helper file into my project, but it would be cleaner to have an export.

**Comment by pimterry** [comment]
Ah, good catch! I can neatly explain this: that script is on the main branch, but it hasn't been released yet, because I forgot :smile:

I'll do that now, it'll be live as v0.2.0 in a few minutes.

**Comment by pimterry** [comment]
Done :rocket:
